### ISSUE TITLE
Add more tests for firebase security rules

### ISSUE THREAD

**Issue by cburgdorf** [machinelabs/machinelabs#775]
#### Bug, feature request, or proposal:

Now that we have [support for testing firebase security rules](https://github.com/machinelabs/machinelabs/pull/772), we should make sure to cover all possible cases. 

#### What is the expected behavior?

Having more tests

- [ ]  /labs
- [x] /invocations
- [x] /executions
- [x] /users (i think)
- [ ] /servers
- [ ] /handshakes
- [ ] /idx
- [ ] /docker_images

#### What is the current behavior?

Only basic test

#### What are the steps to reproduce?

Run test suite :)

#### What is the use-case or motivation for changing an existing behavior?

Better test coverage

#### Which version of MachineLabs (or the package) is affected ?

latest

**Comment by PascalPrecht** [comment]
Hi @maartentibau,

super cool you want to help out with this. I think generally it's good to have tests for all of our security rules. Those rules can be derived from the `read()` and `write()` conditions in `firebase/rules/database.rules.bolt`.

For example the following security rules describe that only the system is allowed to read and write invocation ids.

```
path /invocations/{id} {
  read() { isSystem() }
  write() { isSystem() }
}
```

Here are some more possible specs:

- `/labs/{id}/common`
  - **read**
    - can only be read by system user or owner of the lab, if lab is private
  - **write**
    - can only be written by owner or system user
    - if owner has no plan (anonymous user), lab can only be written if it's not set to private (`is_private = true`)
    - if owner has plan and lab is set private, plan needs to be higher than beta plan (right now this is just `hasPlan() && !hasBetaPlan()`
- `/idx/invocation_rate_proof/{userId}`
  - **read**
    - can only be read by authenticated users
  - **write**
    - can only be written by authenticated users
- `/executions/{id}/common`
  - **read**
    - can only be read if corresponding lab is not private or
    - if corresponding lab is private, reader has to be the owner and a higher plan than beta plan
    - System user can always read
  - **write**
    - can only be written by owner or system user
- `/executions/{id}/messages`
  - **write**
    - can only be written by system user (test that other users can not write)

Hope this helps to get you started @maartentibau !

**Comment by d3lm** [comment]
If you want to test the system user you can create a user object and set the ID to `SYSTEM_USER`. Here's how it could look like in your tests:

```
const systemUser = {
    uid: 'SYSTEM_USER,
    id: 1
  },
```

And then you can use this to test if that particular user can read / write to certain nodes. For example

```
expect(systemUser).canRead('/invocations/1');

// Make sure the dummy invocation has the correct format
expect(systemUser).canWrite('/invocations/1/common', dummyInvocation);

expect(currentUser).cannotRead('/invocations/1');
expect(currentUser).cannotWrite('/invocations/1/common', dummyInvocation);
```

Hope this helps you!

**Comment by PascalPrecht** [comment]
Hey @maartentibau 

just checking in here.. Are you still interested in pushing this forward?

**Comment by maartentibau** [comment]
Hi @PascalPrecht yes.. for sure, but I'm facing some trouble understanding the errors I get with failing tests. Have tried to contact @d3lm, but we didn't yet found a time to have a chat. If you might have some time this evening to have a Skype chat, that would be great to get me started.

**Comment by maartentibau** [comment]
@cburgdorf that works, thx! But when I do the import (via WebStorm) the path is always 

`import { Invocation, InvocationType } from '@machinelabs/models/src';` and not without the `src` like I see everywhere in the code.

Also, when I run my tests I get this error

```
 /Users/webtrix/GitHub/machinelabs/firebase/rules/node_modules/@machinelabs/models/src/index.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './execution';

SyntaxError: Unexpected token export at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)at Object.<anonymous> (tests/invocations.spec.ts:14:13)
```

**Comment by PascalPrecht** [comment]
> Also I noticed that the property directory of the model InvocationLab is typed as File[], but in the rules it's just a string, will this change in the future?

I think there's a couple of things to say about this:

1. I think, actually, `InvocationLab.directory` should be rather of type `LabDirectory`, which is essentially `Array<File | Directory>`. This is because a directory is not just a list of files, but a list of files and other directories. My guess is, that this is just a left over and should be changed to `LabDirectory`. The `LabDirectory` type can be imported from `@machinelabs/models` as well - specifically here: https://github.com/machinelabs/machinelabs/blob/master/shared/models/src/directory.ts#L18

2. Before the data of an invocation is stored in the database, the `directory` gets stringified on purpose (https://github.com/machinelabs/machinelabs/blob/master/client/src/app/editor/remote-code-execution/remote-lab-exec.service.ts#L56). On of the reasons is that you can't store recursive data structures in Firebase database easily, plus, if I remember correctly (/cc'ing @cburgdorf for correctness) there's some limitation on how many levels deep you can go with your nodes. By stringifying the directory, we basically just have to handle one long string that is, at the time of saving, deterministic. This also means that we parse the data again when we pull it out of the database (https://github.com/machinelabs/machinelabs/blob/master/client/src/app/editor/remote-code-execution/remote-lab-exec.service.ts#L124-L126).

So to answer your question, this is not something we want to change in the future.

> import { Invocation, InvocationType } from '@machinelabs/models/src'; and not without the src like I see everywhere in the code.

Yes, you need to import from `@machinelabs/models`. This requires you to, as @cburgdorf said, link `@machinelabs/models` as a dependency. Also, the source of that package needs to be build accordingly. For that you can run the `build.js` script in `shared`.

I assume that'll fix your error as well.

**Comment by maartentibau** [comment]
I think I've covered all test cases for the 'invocations', could you guys maybe have a look and tell me if what I'm doing is what you're expecting? Or if you have remarks or tips, feel free to poke me 😉

**Comment by PascalPrecht** [comment]
That's awesome @maartentibau!

I'll have a look at it today.

On Twitter you asked me a question, let me echo it here so we can keep track of things:

> Whats actually the difference between /invocations/1/common and /invocations/1 ?

So you'll notice that not only `/invocations` but also other nodes in our system follow this pattern of having a `/common` and `/protected` child node respectively. This is due to how firebase rules and validation cascading works. For example, if `/invocations` is readable, all its child nodes will be readable as well. 

That's because, unlike Firebase FireStore, Firebase Realtime Database isn't a document based database. Which means, you can't perform queries that only fetch a subset of a certain nodes without its children.

So in order to have nodes that have both, data that should be readable (by everyone), but also data that's considered protected, you can work around this by creating child nodes for public and protected access respectively. 

`/invocations/{id}/common` is therefore considered "readable", "public" data. `/invocations/{id}/protected` is considered protected data and not readable by everyone.

The names `common` and `protected` are somewhat  arbitrary if you will. We could've called them "public" and "private as well. For semantic reasons however, we went with "common" and "protected".

Here's another concrete example from the past, in case you're interested to follow up on this: https://github.com/machinelabs/machinelabs/pull/140#issuecomment-303223367

Hope this answers your question.
